entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

http:
  routers:
    http-catchall:
      rule: hostregexp(`{host:.+}`)
      entrypoints:
      - http
#      middlewares:
#      - redirect-to-https
#  middlewares:
#    redirect-to-https:
#      redirectScheme:
#        scheme: https
#        permanent: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

#certificatesResolvers:
#  letsEncrypt:
#    acme:
#      email: postmaster@example.com
#      storage: acme.json
#      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
#      httpChallenge:
#        entryPoint: http

api:
  dashboard: true
#  insecure=true
tracing:
  jaeger: {}

accessLog:
  filePath: "/opt/tracing/traefik/access.log"
  format: json
